- README.md
This PR updates the README with the following changes:
* adds a section describing the new features after PR #8 and #15.
* temporarily removes the section on periodic coordinates, since it's been removed in the alpaka version (but will be re-implemented soon)
* fixes image path that were broken on PyPi
* add link to CLUE paper
> Update readme post Alpaka implementation

- CLUEstering/alpaka/CLUE/CLUEAlpakaKernels.h
This PR adds a checks that the energy of a point in a search box is positive, in the case that two energy values are identical.
This has shown to be needed when clustering points representing image pixels.
It also fixes a small typo.
> Change nearest higher found criteria

- CLUEstering/CLUEstering.py
- setup.py
This PR:
* adds a setter for the CLUE parameters in the `clusterer` class (issue #31).
* adds getters for the attributes of the `clust_data` and `clust_prop` members of the clusterer (issue #32).
> Additions to the python interface

- CLUEstering/CLUEstering.py
- setup.py
This PR adds two memebers to the `cluster_properties` member of the `clusterer`:
* `clusters`, which is an array containing the indices of the found clusters. This is useful to loop over the clusters.
* `n_seeds`, which is the number of seeds found. The difference with `n_clusters` is that this doesn't count the set of outliers as a cluster.
* update the equality operator of `cluster_properties` to also check `n_seeds`
> Adding `n_seeds` and `clusters` members to clusterer

- .github/workflows/check_package_version.yml
This PR implements a workflow which checks whether the version in `setup.py` was updated.
The workflow fails if the versions in the PR is equal or behind the version in the main branch.
It's only run on pull requests, not on the main branch.
> Add version checking CI/CD workflow

- CLUEstering/CLUEstering.py
- setup.py
This PR fixes the input data type as 32 bits float. This is done in order to avoid wrong integer conversions when scaling the coordinates. Closes issue #51.
> Specify input data type as float

- CLUEstering/alpaka/CLUE/CLUEAlgoAlpaka.h
- CLUEstering/alpaka/CLUE/Run.h
- benchmark/dataset_size/main.cc
- benchmark/profiling/main.cc
The CLUEAlgoAlpaka class is currently templated on the accelerator type. This is unnecessary and makes it more complicated to use the C++ backend directly, so this PR removes it.
> Remove `CLUEAlgoAlpaka` template on acc type

- .gitattributes
Add a `.gitattributes` file containing a list of files and folders that don't need to be included in releases tarballs, so to reduce the resulting size.
> Add list of files to exclude in archives

- .gitignore
- CLUEstering/CLUEstering.py
- setup.py
- tests/test_clusterer_import.py
This PR adds a method to the Python API for importing the results of a clustering done previously and saved to a csv file using the `to_csv` method.
NOTE: it also adds the weight columnt to the csv generated with `to_csv`.
> Feature clusterer import method

- include/CLUEstering/CLUE/CLUEAlpakaKernels.hpp
- include/CLUEstering/CLUEstering.hpp
- include/CLUEstering/DataFormats/alpaka/PointsAlpaka.hpp
in `CLUEAlgoAlpaka`:
- add `getClusters` method 
- have the device points as a member
also:
- take `PointsAlpakaView` out of `PointsAlpaka`
> Add `getClusters` methods and enhance general interface

- .github/workflows/bench_profile_serial.yml
- .github/workflows/python-package.yml
- CLUEstering/BindingModules/binding_cpu_omp.cpp
- CLUEstering/CLUEstering.py
- CMakeLists.txt
- benchmark/dataset_size/CMakeLists.txt
- benchmark/profiling/CMakeLists.txt
- include/CLUEstering/test/CMakeLists.txt
This PR adds the alpaka-based OpenMP backed for parallel execution on CPU, which serves as an alternative for the TBB backend.
> Feature Alpaka-OpenMP backend

- CMakeLists.txt
- benchmark/dataset_size/CMakeLists.txt
- benchmark/profiling/CMakeLists.txt
The benchmark below shows that enabling auto-vectorization and loop-unrolling gives a non-negligible boost in performance for the serial backend
> Allow automatic vectorization and loop unrolling

- CLUEstering/BindingModules/Run.hpp
- benchmark/dataset_size/main.cpp
- benchmark/profiling/main.cpp
- include/CLUEstering/CLUE/CLUEAlpakaKernels.hpp
- include/CLUEstering/CLUEstering.hpp
- include/CLUEstering/DataFormats/alpaka/PointsAlpaka.hpp
- include/CLUEstering/DataFormats/alpaka/TilesAlpaka.hpp
This PR moves the TilesAlpaka and PointsAlpaka classes in the `clue` namespace instead of `ALPAKA_ACCELERATOR_NAMESPACE`. This will be needed by later PRs extending the C++ interface for making it less cumbersome to use.
> Remove ALPAKA_ACCELERATOR_NAMESPACE from PointsAlpaka and TilesAlpaka

- benchmark/dataset_size/CMakeLists.txt
- benchmark/dataset_size/cpu/CMakeLists.txt
- benchmark/dataset_size/cuda/CMakeLists.txt
- benchmark/dataset_size/main.cpp
- benchmark/dataset_size/pybind11
- benchmark/dataset_size/sycl/CMakeLists.txt
- benchmark/dataset_size/sycl/pybind11
Use pybind11 to produce plots of benchmark results only if it's installed globally on the machine.
> Only plot dset bench results if pybind globally available

- CLUEstering/BindingModules/Run.hpp
- CLUEstering/BindingModules/cuda/binding_gpu_cuda.cpp
- CLUEstering/BindingModules/hip/binding_gpu_hip.cpp
- CLUEstering/BindingModules/openmp/binding_cpu_omp.cpp
- CLUEstering/BindingModules/serial/binding_cpu.cpp
- CLUEstering/BindingModules/tbb/binding_cpu_tbb.cpp
- CLUEstering/CLUEstering.py
- benchmark/dataset_size/main.cpp
- benchmark/profiling/main.cpp
- include/CLUEstering/CLUE/CLUEAlpakaKernels.hpp
- include/CLUEstering/CLUEstering.hpp
- tests/test_clustering.cpp
This PR separates the `dc` parameter in two:
* the usual one, now only used for the calculation of local density
* a new one, `seed_dc` used in the kernel for finding clusters
* also, reorder the clusterer constructor arguments, putting the Queue as first argument
* default initialize `pointsPerTile` to 128
> Add `seed_dc` parameter and reorder `Clusterer` constructor arguments

- include/CLUEstering/CLUE/CLUEAlpakaKernels.hpp
This PR modifies the kernel for the calculation of local density in order to improve vectorization.
> Allow vectorization in density kernel

- include/CLUEstering/CLUE/CLUEAlpakaKernels.hpp
- include/CLUEstering/DataFormats/alpaka/TilesAlpaka.hpp
Since most methods of `std::array` are constexpr, it can be used in device code as well without needing to use raw pointers.
> Use `std::array` for allocating coordinates in kernels

- include/CLUEstering/CLUE/CLUEAlpakaKernels.hpp
- include/CLUEstering/DataFormats/alpaka/SearchBox.hpp
- include/CLUEstering/DataFormats/alpaka/TilesAlpaka.hpp
This PR defines a `SearchBox` class based on `std::array`, aiming at making the code easier to read, substituting the more ambiguous use of `VecArray`s.
> Rework searchbox struct using `std::array`

- tests/CMakeLists.txt
- tests/cpu/CMakeLists.txt
- tests/cuda/CMakeLists.txt
- tests/test_clusterer.cpp
- tests/test_clustering.cpp
In order to maintain retro-compatibility when testing on machine with older compiler versions, for now we should use `fmt::format` instead of `std::format`.
> Use `fmt::format` instead of `std::format` in tests

- include/CLUEstering/CLUE/CLUEAlpakaKernels.hpp
- include/CLUEstering/DataFormats/alpaka/TilesAlpaka.hpp
- include/CLUEstering/detail/make_array.hpp
In some configuration the assignment of arrays to search boxes with brace initalizations caused compilation errors. This PR fixes this.
> Define `make_array` utility in `nostd` namespace

- benchmark/dataset_size/cpu/CMakeLists.txt
- benchmark/dataset_size/cuda/CMakeLists.txt
- benchmark/dataset_size/main.cpp
- benchmark/dataset_size/sycl/CMakeLists.txt
- benchmark/utils/generation.hpp
In order to be able to benchmark large dataset sizes without making the repository heavier with large csv files, this PR provides data generators for generating random datasets when executing the benchmarks.
The already existing datasets are still available for testing and profiling (where reproducible results are needed).
> Implement data generators for benchmarks of dataset size

- include/CLUEstering/CLUE/CLUEAlpakaKernels.hpp
- include/CLUEstering/CLUEstering.hpp
- include/CLUEstering/DataFormats/alpaka/AssociationMap.hpp
- include/CLUEstering/DataFormats/alpaka/Followers.hpp
This PR reworks the Followers buffer using an association map. Before the Followers were a buffer of compile-time-sized VecArrays, which implied a big waste of memory and hindered the generality of the code. Now the Followers occupy just 2% of the memory they required before, and are completely built at runtime.
Furthermore, benchmarks show comparable or even better performance:
> Rework followers using AssociatonMap

- include/CLUEstering/AlpakaCore/CachingAllocator.hpp
- include/CLUEstering/CLUE/CLUEAlpakaKernels.hpp
- include/CLUEstering/CLUEstering.hpp
- include/CLUEstering/DataFormats/Common.hpp
- include/CLUEstering/DataFormats/PointsDevice.hpp
- include/CLUEstering/DataFormats/PointsHost.hpp
- include/CLUEstering/DataFormats/alpaka/AssociationMap.hpp
- include/CLUEstering/DataFormats/alpaka/Followers.hpp
- include/CLUEstering/DataFormats/alpaka/TilesAlpaka.hpp
To reduce the (although small) overhead due to excessive reference-counting and creation-destruction of the underlying streams, from now on alpaka Queues are passed by reference.
> Pass alpaka Queues by reference

- include/CLUEstering/internal/math/defines.hpp
- include/CLUEstering/internal/math/exp/exp.hpp
- include/CLUEstering/internal/math/max/max.hpp
- include/CLUEstering/internal/math/min/min.hpp
- include/CLUEstering/internal/math/pow/pow.hpp
- include/CLUEstering/internal/math/sqrt/sqrt.hpp
This PR uses backend specific macros to only compile the functions in `internal/math` when they are called inside device code.
> Compile internal `math` functions only inside device code

- CLUEstering/BindingModules/Run.hpp
- CLUEstering/BindingModules/cuda/binding_gpu_cuda.cpp
- CLUEstering/BindingModules/hip/binding_gpu_hip.cpp
- CLUEstering/BindingModules/openmp/binding_cpu_omp.cpp
- CLUEstering/BindingModules/serial/binding_cpu.cpp
- CLUEstering/BindingModules/tbb/binding_cpu_tbb.cpp
- benchmark/dataset_size/main.cpp
- benchmark/profiling/main.cpp
- include/CLUEstering/CLUEstering.hpp
- include/CLUEstering/core/CLUEAlpakaKernels.hpp
- include/CLUEstering/core/Clusterer.hpp
- include/CLUEstering/core/defines.hpp
- include/CLUEstering/internal/alpaka/config.hpp
- tests/test_clusterer.cpp
- tests/test_clustering.cpp
- tests/test_device_points.cpp
- tests/test_host_points.cpp
This PR removes the `ALPAKA_ACCELERATOR_NAMESPACE`, as it's not needed anymore, and this simplifies noticeably the backend.
It also makes the `Queue`, `Platform`, `Device` and `Event` type publicly available in the `clue` namespace.
> Remove alpaka accelerator namespace and move definitions in `clue::internal`

- .github/workflows/check_package_version.yml
The version checking workflow now passes even if the version was not changed
> Update passing conditions for version checking workflow

- include/CLUEstering/core/Clusterer.hpp
- include/CLUEstering/core/ConvolutionalKernel.hpp
- include/CLUEstering/core/detail/CLUEAlpakaKernels.hpp
- include/CLUEstering/core/detail/Clusterer.hpp
- include/CLUEstering/core/detail/ConvolutionalKernel.hpp
- include/CLUEstering/data_structures/AssociationMap.hpp
- include/CLUEstering/data_structures/PointsDevice.hpp
- include/CLUEstering/data_structures/PointsHost.hpp
- include/CLUEstering/data_structures/detail/AssociationMap.hpp
- include/CLUEstering/data_structures/detail/PointsDevice.hpp
- include/CLUEstering/data_structures/detail/PointsHost.hpp
- include/CLUEstering/utils/detail/read_csv.hpp
- include/CLUEstering/utils/read_csv.hpp
This PR separates the declarations and definitions of the classes, functions and methods that are part of the public interface. The implementation details are hidden inside `detail` subfolders. This will be useful when implementing documentation for the C++ interface, and will allow the backend to remain sufficiently clean.
> Separate declaration and implementation details of public classes

- .github/workflows/cmake-format-check.yml
The workflow will run cmake-format on all the CMakeLists.txt file present in release. If differences are spotted between the formatted files and the PR file, it will fail, suggesting to run cmake-format on the specific files. It will also upload a patch file in artifacts that the user can download and apply
> Adding New CI/CD workflow checking cmake file formatting

- CLUEstering/BindingModules/Run.hpp
- benchmark/dataset_size/main.cpp
- benchmark/profiling/main.cpp
- include/CLUEstering/data_structures/AssociationMap.hpp
- include/CLUEstering/data_structures/PointsDevice.hpp
- tests/test_clusterer.cpp
- tests/test_clustering.cpp
- tests/test_device_points.cpp
- tests/test_utilities.cpp
Since the `ALPAKA_ACCELERATOR_NAMESPACE` has been removed in PR #151, now the template parameters for the `clue::PointsDevice` and `clue::AssociationMap` data structures can be easily defaulted to `clue::Device`.
This will make the interface cleaner for users.
> Default device template parameter of `PointsDevice` and `AssociationMap` to `clue::Device`

- CLUEstering/CLUEstering.py
This PR adds a parameter to the plotting functions which allows to save the plot as file instead of showing it (issue #24).
> Include option for saving plots as files

- CLUEstering/BindingModules/Run.hpp
- benchmark/dataset_size/main.cpp
- benchmark/profiling/main.cpp
- docs/getting-started.dox
- examples/main.cpp
- include/CLUEstering/core/Clusterer.hpp
- include/CLUEstering/core/detail/Clusterer.hpp
- tests/test_clusterer.cpp
- tests/test_clustering.cpp
This PR:
* reorders the arguments of all the `make_clusters` overloads, putting the queue as the first argument
* provides a default argument for the convolutional kernel, defaulting it to `FlatKernel` with parameter `.5f`
NOTE: this is an API-breaking change
> Reorder `make_clusters` arguments and provide default value to convolutional kernel

- include/CLUEstering/core/Clusterer.hpp
- include/CLUEstering/core/detail/Clusterer.hpp
- include/CLUEstering/core/detail/ComputeTiles.hpp
This PR uses `reduce` instead of `max/min_element` in the calculation of the tile sizes. It also changes the function from a method of the Clusterer to a free function.
> Use reduce instead of extrema algorithms when calculating tiles

- include/CLUEstering/core/detail/ComputeTiles.hpp
- include/CLUEstering/internal/algorithm/default_policy.hpp
- include/CLUEstering/internal/algorithm/extrema/extrema.hpp
- include/CLUEstering/internal/algorithm/reduce/reduce.hpp
- include/CLUEstering/internal/algorithm/sort/sort.hpp
Currently the algorithms used internally use the `std::execution::unseq` policy. With this PR, a `default_policy` is defined, which expands to `std::execution::par_unseq` when the TBB backend is used, which assures that TBB will be linked in the final executable. This policy is also used in the CPU expansion of the internal algorithm wrappers.
> Define default execution policy for internal use of std algorithms

- CLUEstering/BindingModules/cuda/CMakeLists.txt
- benchmark/dataset_size/cuda/CMakeLists.txt
- benchmark/profiling/cuda/CMakeLists.txt
- examples/CMakeLists.txt
- tests/cuda/CMakeLists.txt
Both internally, as well as during the installation of the Python library, we were still building the CUDA backend for old cuda capabilities (50, 60, ...). Now we only compile for `sm_75/80/90`
> Only compile for cuda architectures from `sm75` onwards

- include/CLUEstering/core/detail/CLUEAlpakaKernels.hpp
- include/CLUEstering/core/detail/Clusterer.hpp
From this PR, when a point is marked as a seed its nearest higher is set to `-1`, and the `Followers` associator is filled after this kernel has completed. This prevents some seeds to be included in the cluster of a very near seed.
> Set nearest higher to `-1` for confirmed seeds
